Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -291,6 +291,20 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Get backend url & Backend smoke test.
+          command: |
+            back_ip=$(curl -H "token: d4a80299-0f25-4edb-8b00-23f64dbac30a" --request GET https://api.memstash.io/values/ec2_bk_${CIRCLE_WORKFLOW_ID:0:7})
+            echo "http://$back_ip:3030/api/status";
+            if curl -s "http://$back_ip:3030/api/status" | grep "ok"
+            then
+              echo "Working"
+            else
+            echo "Error!"
+            echo curl -s "http://$back_ip:3030/api/status";
+            curl -vvv "http://$back_ip:3030/api/status"
+            exit 1
+            fi
+      - run:
           name: Frontend smoke test.
           command: |
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
@@ -300,6 +314,8 @@ jobs:
             else
               exit 1
             fi
+      - destroy-environment
+      - revert-migrations
 
   cloudfront-update:
     docker:
@@ -310,14 +326,17 @@ jobs:
           name: Update cloudfront distribution
           command: |
             old_workflow_id=$(aws cloudformation list-exports --query "Exports[?Name==\`WorkflowID\`].Value" --no-paginate --output text)
+            echo "$old_workflow_id"
             if [ -z $old_workflow_id ]
             then
+              echo "inside 1"
               aws cloudformation deploy \
               --template-file .circleci/files/cloudfront.yml \
               --stack-name "Udapeople-Cloudfront" \
               --region ${AWS_DEFAULT_REGION} \
               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
             else
+              echo "inside 2"
               aws cloudformation delete-stack --stack-name Udapeople-Cloudfront
               sleep 60
               aws cloudformation deploy \
